### ISSUE TITLE
【严重】（管理门户）登录-资源管理-资源中心部署-初始化（场景：5台机器，slave从核心域中取一台），提示：clientError-400:bad request

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-BE-RM#3]
环境：win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.248:16002/paas-console
登录-用户：chy 密码：123456
步骤：
1.登录系统
2,.进入资源管理-资源中心部署-初始化（场景：5台机器，slave从核心域中取一台）
实际结果：提示：clientError-400:bad request
预期结果：初始化成功

**Comment by yuanman001** [comment]
问题已解决，paas-cdep工程的project.properties文件所增加的project.task.root=http://127.0.0.1:16009/paas-task变量，结尾不能存在空格。

**Comment by chenhy6** [comment]
验证通过
