### ISSUE TITLE
［一般］（管理门户）登录-资源管理-资源中心部署-初始化-列表－点击“标签详情”，不起作用

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-BE-RM#4]
环境：win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.248:16002/paas-console
登录-用户：chy 密码：123456
步骤：
1.登录系统
2.进入，资源管理-资源中心部署-初始化-列表－点击“标签详情”，
实际结果：
点击“标签详情”，不起作用
预期结果：
可查看到详情信息

**Comment by yuanman001** [comment]
此功能后续添加，目前暂不测试，已隐藏按钮。

**Comment by chenhy6** [comment]
通过
